### ISSUE TITLE
bad error message n.fc >= 0

### ISSUE THREAD

**Issue by ronaldindergand** [christophsax/tempdisagg#15]
should return meaningful error or omit annual value

```
   td(agric_n ~ window(ppi_lw, end = c(2011, 1))
     Error: n.fc >= 0 is not TRUE 
```

**Comment by bhuston** [comment]
Chris,

I have two series (l.f., h.f) which are highly exactly the same length and am getting this  
> Error: n.fc >= 0 is not TRUE 

issue.  I have tried sample reduction (making my l.f. even shorter than h.f) and and everything still fails.  Any other possible things that could be throwing this error?

Thanks,
Ben

**Comment by bhuston** [comment]
I should correct myself.  My h.f series is exactly an integer multiple of 30 longer than my l.f.  I have also tired the case where the h.f. was greater than 30 multple (eg, 30.74) than l.f and still get same issue.

**Comment by christophsax** [comment]
Hi Ben, thanks for the report. Can you give me a reproducible example? That would be very helpful. Christoph

**Comment by bhuston** [comment]
Thanks for the follow up Chris.

I actually figured out what was causing the issue.  I simply needed to explicitly use the as.vector() function within td().  I had previously used just unlist() on my input vectors but apparently this wasn't good enough.

As for the example, I am rushed to get something to a co-author of mine right now so I am cannot put together a 100% reproducible one with dummy data.  However, I post below my code which gives the gist of how I got around the error.

>    # subsetting from dataframes of monthly and daily time series
>Low <- na.omit(CCAdata_GAM[, c("edfdate", "us_unemployment_rate")]) 
>High <- na.omit(CCAdata_GAM[, c("edfdate", "us_3m_tbill_yield")])
>
>A <- nrow(Low)*30 # find adjustment factor to make high series exact multiple of short one
>B <- nrow(High)
>High <- rbind(High, High[ (B-(A-B)):(B-1),])                
>A <- nrow(Low)*30
>B <- nrow(High)
>A-B # should equal zero
>
>temp1 <- td( as.vector(Low[,2][1:100]) ~ as.vector(High[,2][1:3000]), to = 30, conversion="last") # using really long series causing memory issues 


Thanks again!  By the way, do you have any advice on memory management for td()?  My plan was to disagg monthly/quarterly series into daily ones for 10 years of data.  However, when I run td() using the exact code above -- without the vector subsetting within in td() -- I completely run out of memory at 64GB.  (I am using a brand-new 10-core server for calculations.  My number of daily obs is about 500,000.)

**Comment by christophsax** [comment]
Thanks, Ben

`High[,2][1:3000]` is probably something different than a vector. You could check it with `class()`. 

Anyway, I would recommend to convert the inputs to time series first, using `ts()`. This will save you some hassle, and makes the `to` argument redundant.

Cheers, Christoph

**Comment by christophsax** [comment]
i am closing this one. There is a new issue on input checks #20 which addresses the cryptic errror message in ben's problem.
